<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="10" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="206" started-at="2017-07-27T12:53:13Z" finished-at="2017-07-27T12:53:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="206" started-at="2017-07-27T12:53:13Z" finished-at="2017-07-27T12:53:13Z">
      <class name="com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest">
        <test-method status="PASS" signature="loadDB()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="loadDB" is-config="true" duration-ms="8" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadDB -->
        <test-method status="FAIL" signature="Team_getActiveMembers_should_return_a_list_of_team_members_that_are_active()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="Team_getActiveMembers_should_return_a_list_of_team_members_that_are_active" duration-ms="67" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[java.lang.Integer cannot be cast to com.qainfotech.tap.training.resourceio.model.Individual]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: java.lang.Integer cannot be cast to com.qainfotech.tap.training.resourceio.model.Individual
	at com.qainfotech.tap.training.resourceio.model.Team.getActiveMembers(Team.java:77)
	at com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest.Team_getActiveMembers_should_return_a_list_of_team_members_that_are_active(TeamsYamlReaderTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Team_getActiveMembers_should_return_a_list_of_team_members_that_are_active -->
        <test-method status="FAIL" signature="Team_getInactiveMembers_should_return_a_list_of_individual_team_members_that_are_inactive()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="Team_getInactiveMembers_should_return_a_list_of_individual_team_members_that_are_inactive" duration-ms="5" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[java.lang.Integer cannot be cast to com.qainfotech.tap.training.resourceio.model.Individual]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: java.lang.Integer cannot be cast to com.qainfotech.tap.training.resourceio.model.Individual
	at com.qainfotech.tap.training.resourceio.model.Team.getInactiveMembers(Team.java:119)
	at com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest.Team_getInactiveMembers_should_return_a_list_of_individual_team_members_that_are_inactive(TeamsYamlReaderTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Team_getInactiveMembers_should_return_a_list_of_individual_team_members_that_are_inactive -->
        <test-method status="PASS" signature="getIndividualById_should_return_Individual_object_matching_id()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getIndividualById_should_return_Individual_object_matching_id" duration-ms="44" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIndividualById_should_return_Individual_object_matching_id -->
        <test-method status="PASS" signature="getIndividualById_should_throw_ObjectNotFoundException_for_incorrect_id()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getIndividualById_should_throw_ObjectNotFoundException_for_incorrect_id" duration-ms="4" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <exception class="com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException">
            <message>
              <![CDATA[Individual Object with id=100 not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException: Individual Object with id=100 not found
	at com.qainfotech.tap.training.resourceio.TeamsYamlReader.getIndividualById(TeamsYamlReader.java:72)
	at com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest.getIndividualById_should_throw_ObjectNotFoundException_for_incorrect_id(TeamsYamlReaderTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIndividualById_should_throw_ObjectNotFoundException_for_incorrect_id -->
        <test-method status="PASS" signature="getIndividualByName_should_return_Individual_object_matching_name()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getIndividualByName_should_return_Individual_object_matching_name" duration-ms="6" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIndividualByName_should_return_Individual_object_matching_name -->
        <test-method status="PASS" signature="getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name" duration-ms="3" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <exception class="com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException">
            <message>
              <![CDATA[Individual Object with Name=Individual By This Name Does Not Exist not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException: Individual Object with Name=Individual By This Name Does Not Exist not found
	at com.qainfotech.tap.training.resourceio.TeamsYamlReader.getIndividualByName(TeamsYamlReader.java:104)
	at com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest.getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name(TeamsYamlReaderTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.resourceio.exceptions.ObjectNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIndividualByName_should_throw_ObjectNotFoundException_for_incorrect_name -->
        <test-method status="PASS" signature="getListOfActiveIndividuals_ahould_return_array_list_of_only_active_individual_objects()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getListOfActiveIndividuals_ahould_return_array_list_of_only_active_individual_objects" duration-ms="6" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListOfActiveIndividuals_ahould_return_array_list_of_only_active_individual_objects -->
        <test-method status="PASS" signature="getListOfInactiveIndividuals_should_return_array_list_of_only_inactive_individual_objects()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getListOfInactiveIndividuals_should_return_array_list_of_only_inactive_individual_objects" duration-ms="10" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListOfInactiveIndividuals_should_return_array_list_of_only_inactive_individual_objects -->
        <test-method status="PASS" signature="getListOfIndividuals_should_return_array_list_of_all_individual_objects()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getListOfIndividuals_should_return_array_list_of_all_individual_objects" duration-ms="13" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListOfIndividuals_should_return_array_list_of_all_individual_objects -->
        <test-method status="PASS" signature="getListOfTeams_should_return_a_list_if_Team_object_from_db_json()[pri:0, instance:com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest@14acaea5]" name="getListOfTeams_should_return_a_list_if_Team_object_from_db_json" duration-ms="11" started-at="2017-07-27T18:23:13Z" finished-at="2017-07-27T18:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListOfTeams_should_return_a_list_if_Team_object_from_db_json -->
      </class> <!-- com.qainfotech.tap.training.resourceio.TeamsYamlReaderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
